apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  annotations:
    crossplane.io/composition-resource-name: rta-us-west-2b-public
    crossplane.io/external-create-pending: "2024-09-26T15:53:03Z"
    crossplane.io/external-create-succeeded: "2024-09-26T15:53:03Z"
    crossplane.io/external-name: rtbassoc-03db7e0cae10856a1
  creationTimestamp: "2024-09-26T15:49:00Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: configuration-aws-network-
  generation: 3
  labels:
    crossplane.io/claim-name: ""
    crossplane.io/claim-namespace: ""
    crossplane.io/composite: configuration-aws-network
    networks.aws.platform.upbound.io/network-id: configuration-aws-network
  name: configuration-aws-network-gxbvb
  ownerReferences:
  - apiVersion: aws.platform.upbound.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XNetwork
    name: configuration-aws-network
    uid: 26d63562-ba4c-4c4e-bd9c-e8c90f98c797
  resourceVersion: "751286"
  uid: 3feee8a2-c2c1-4c2b-8e82-1acaef9b6d77
spec:
  deletionPolicy: Delete
  forProvider:
    region: us-west-2
    routeTableId: rtb-0b071e65c07335818
    routeTableIdRef:
      name: configuration-aws-network-tzdwz
    routeTableIdSelector:
      matchControllerRef: true
    subnetId: subnet-0ec8a7d7839f6d8cf
    subnetIdRef:
      name: configuration-aws-network-6l28q
    subnetIdSelector:
      matchControllerRef: true
      matchLabels:
        access: public
        zone: us-west-2b
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
status:
  atProvider:
    gatewayId: ""
    id: rtbassoc-03db7e0cae10856a1
    routeTableId: rtb-0b071e65c07335818
    subnetId: subnet-0ec8a7d7839f6d8cf
  conditions:
  - lastTransitionTime: "2024-09-26T15:53:03Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2024-09-26T15:53:08Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-09-26T15:53:05Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
