apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  annotations:
    crossplane.io/composition-resource-name: sgrm
    crossplane.io/external-create-pending: "2024-09-26T15:53:03Z"
    crossplane.io/external-create-succeeded: "2024-09-26T15:53:03Z"
    crossplane.io/external-name: sgrule-1341494646
  creationTimestamp: "2024-09-26T15:49:00Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: configuration-aws-network-
  generation: 3
  labels:
    crossplane.io/claim-name: ""
    crossplane.io/claim-namespace: ""
    crossplane.io/composite: configuration-aws-network
    networks.aws.platform.upbound.io/network-id: configuration-aws-network
  name: configuration-aws-network-s7cpp
  ownerReferences:
  - apiVersion: aws.platform.upbound.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XNetwork
    name: configuration-aws-network
    uid: 26d63562-ba4c-4c4e-bd9c-e8c90f98c797
  resourceVersion: "751306"
  uid: aed8f116-1047-46b1-9781-79da6ece94b8
spec:
  deletionPolicy: Delete
  forProvider:
    cidrBlocks:
    - 0.0.0.0/0
    description: Everywhere
    fromPort: 3306
    protocol: tcp
    region: us-west-2
    securityGroupId: sg-0f048301b762a1c7c
    securityGroupIdRef:
      name: configuration-aws-network-pbbvn
    securityGroupIdSelector:
      matchControllerRef: true
    toPort: 3306
    type: ingress
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
status:
  atProvider:
    cidrBlocks:
    - 0.0.0.0/0
    description: Everywhere
    fromPort: 3306
    id: sgrule-1341494646
    protocol: tcp
    securityGroupId: sg-0f048301b762a1c7c
    securityGroupRuleId: sgr-01d0ccce3c9785a14
    self: false
    toPort: 3306
    type: ingress
  conditions:
  - lastTransitionTime: "2024-09-26T15:53:03Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2024-09-26T15:53:12Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-09-26T15:53:08Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
