apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  annotations:
    crossplane.io/composition-resource-name: vpc
    crossplane.io/external-create-pending: "2024-09-26T15:51:03Z"
    crossplane.io/external-create-succeeded: "2024-09-26T15:51:03Z"
    crossplane.io/external-name: vpc-0ba6a91df9e9ba07e
  creationTimestamp: "2024-09-26T15:49:00Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: configuration-aws-network-
  generation: 3
  labels:
    crossplane.io/claim-name: ""
    crossplane.io/claim-namespace: ""
    crossplane.io/composite: configuration-aws-network
    networks.aws.platform.upbound.io/network-id: configuration-aws-network
  name: configuration-aws-network-8b25q
  ownerReferences:
  - apiVersion: aws.platform.upbound.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XNetwork
    name: configuration-aws-network
    uid: 26d63562-ba4c-4c4e-bd9c-e8c90f98c797
  resourceVersion: "750883"
  uid: 67d0d058-c9cb-4611-8074-eaa7640f4d5e
spec:
  deletionPolicy: Delete
  forProvider:
    cidrBlock: 192.168.0.0/16
    enableDnsHostnames: true
    enableDnsSupport: true
    instanceTenancy: default
    region: us-west-2
    tags:
      Name: configuration-aws-network
      crossplane-kind: vpc.ec2.aws.upbound.io
      crossplane-name: configuration-aws-network-8b25q
      crossplane-providerconfig: default
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
status:
  atProvider:
    arn: arn:aws:ec2:us-west-2:123456789012:vpc/vpc-0ba6a91df9e9ba07e
    assignGeneratedIpv6CidrBlock: false
    cidrBlock: 192.168.0.0/16
    defaultNetworkAclId: acl-0f97e9ccc3d0aeffd
    defaultRouteTableId: rtb-053e0cf4c232831af
    defaultSecurityGroupId: sg-0e0be4389ecb056cf
    dhcpOptionsId: dopt-0c388774
    enableDnsHostnames: true
    enableDnsSupport: true
    enableNetworkAddressUsageMetrics: false
    id: vpc-0ba6a91df9e9ba07e
    instanceTenancy: default
    ipv6AssociationId: ""
    ipv6CidrBlock: ""
    ipv6CidrBlockNetworkBorderGroup: ""
    ipv6IpamPoolId: ""
    ipv6NetmaskLength: 0
    mainRouteTableId: rtb-053e0cf4c232831af
    ownerId: "123456789012"
    tags:
      Name: configuration-aws-network
      crossplane-kind: vpc.ec2.aws.upbound.io
      crossplane-name: configuration-aws-network-8b25q
      crossplane-providerconfig: default
      external-tag-1: test
      external-tag-2: test-2
    tagsAll:
      Name: configuration-aws-network
      crossplane-kind: vpc.ec2.aws.upbound.io
      crossplane-name: configuration-aws-network-8b25q
      crossplane-providerconfig: default
  conditions:
  - lastTransitionTime: "2024-09-26T15:51:03Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2024-09-26T15:51:25Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-09-26T15:51:18Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
