package render

// AWSResourceFilterTemplate is a Go text/template for generating filters for AWS resources.
const AWSResourceFilterTemplate = `// Package filters 
// auto-generated
package filters

// NewAWSResourceFilter returns a map of resources that support tags.
// these values were generated by querying the AWS CRDs for spec.forProvider.tags support.
func NewAWSResourceFilter() ResourceFilter {
    return ResourceFilter{
    {{- range . }}
        "{{.GroupKind}}": {{.Enabled}},
    {{- end }}
    }
}
`
