apiVersion: aws.platform.upbound.io/v1alpha1
kind: XNetwork
metadata:
  name: configuration-aws-network
spec:
  parameters:
    additionalTags:
      replaceFromXR: value1
      replaceFromXR2: value2
      add: me
    optionalTags:
      retainFromXR: optional1
      retainFromXR2: optional2
    ignoreTagKeysReplace:
    - ignoreReplace1
    - ignoreReplace2
    # if there is a conflict, keep the existing tags
    ignoreTagKeysRetain:
    - ignoreRetain1
    id: configuration-aws-network
    region: us-west-2
    vpcCidrBlock: 192.168.0.0/16
    subnets:
      - availabilityZone: us-west-2a
        type: public
        cidrBlock: 192.168.0.0/18
      - availabilityZone: us-west-2b
        type: public
        cidrBlock: 192.168.64.0/18
      - availabilityZone: us-west-2a
        type: private
        cidrBlock: 192.168.128.0/18
      - availabilityZone: us-west-2b
        type: private
        cidrBlock: 192.168.192.0/18
