// Package filters determines whether resources support tags
package filters

// ResourceFilter is a map indicating whether a resource supports tags.
type ResourceFilter map[string]bool

// NewResourceFilter returns a map of resources that support tags.
// these values were generated by querying Provider CRDs for `spec.forProvider.tags` support.
func NewResourceFilter() ResourceFilter {
	return NewAWSResourceFilter()
}
